"""Convert raw openResource/getById JSONs (docs/api-raw/<apiId>.json) into
clean markdown scaffolds at docs/api/<group>/<name>.md.

Each generated file has the upstream contract (URL / method / params / sample
response) at the top, followed by an `## Integration notes` section that's
left empty for hand editing.

Run from repo root:
    python3 scripts/render_endpoint_docs.py

Idempotent: re-runs preserve any text below the `## Integration notes` marker.
"""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
RAW = REPO / "docs" / "api-raw"
OUT = REPO / "docs" / "api"

# apiId → (group_dir, file_slug). Mirrors docs/api/README.md.
LAYOUT: dict[str, tuple[str, str]] = {
    # Admin / bootstrap
    "2008047481493000192": ("admin", "role-listByCompany"),
    "2007738179096023040": ("admin", "user-registMember"),
    "2018918321059139584": ("admin", "open-queryMemberKey"),
    "2018510774972059648": ("admin", "open-memberToken-get"),
    "2018600393214398464": ("admin", "open-memberToken-refresh"),
    # Public data
    "2011714836790120448": ("public", "getAllUnits"),
    "2011773533461549056": ("public", "getAllocationVersions"),
    "2011706323401576448": ("public", "getAssignedCalculationMethods"),
    # Spaces
    "2010653094400102400": ("spaces", "getProjectSpaces"),
    "2011014051538276352": ("spaces", "addProjectSpace"),
    "2011982334475243520": ("spaces", "getAllUser"),
    "2011985039088291840": ("spaces", "addMemberToSpaceBatch"),
    "2011989312329093120": ("spaces", "getMembersBySpaceId"),
    "2037006616536158208": ("spaces", "deleteMemberFromSpaceBatch"),
    "2011987493901176832": ("spaces", "updateMemberRole"),
    # Models
    "2011279970709671936": ("models", "getModelList"),
    # Products
    "2011335695137902592": ("products", "addBrand"),
    "2011338264501424128": ("products", "getBrandPage"),
    "2011348255354523648": ("products", "getBrandInfo"),
    "2011361550383845376": ("products", "getCaseDetail"),
    "2036745394263822336": ("products", "copyCase"),
    "2011363705077501952": ("products", "getCaseStage"),
    "2037000724835078144": ("products", "deleteCase"),
    "2011371802932154368": ("products", "getProcessList"),
    "2011760183805612032": ("products", "getDataConfigurationList"),
    "2011764816800256000": ("products", "getDataConfigurationDetail"),
    # Data input
    "2011641035020701696": ("data", "getElementList"),
    "2011674152901152768": ("data", "editElements"),
    "2011677750871592960": ("data", "exportElementData"),
    "2011679830789197824": ("data", "importModelData"),
    # Submit calculation
    "2011696470046150656": ("calc", "getCaseDisposals"),
    "2011694047529406464": ("calc", "addCaseCalculationTask"),
    "2011737258226487296": ("calc", "getCaseCalculationMethods"),
    "2011734808333520896": ("calc", "getCaseLciaDetails"),
    "2037035500149280768": ("calc", "publishData"),
    "2037037419831889920": ("calc", "getCaseSensitive"),
    # Uncertainty
    "2011741052771373056": ("uncertainty", "submitUncertaintyAnalysis"),
}

# Marker that separates auto-generated content from hand-edited content.
INTEGRATION_HEADER = "## Integration notes"

HTML_TAG = re.compile(r"<[^>]+>")
WS = re.compile(r"\s+")


def html_to_text(s: str) -> str:
    """Crude HTML → plain text. Good enough for table rows the docs use."""
    s = HTML_TAG.sub(" ", s)
    s = html.unescape(s)
    return WS.sub(" ", s).strip()


def extract_field(desc_html: str, label: str) -> str | None:
    """Pull a single labeled cell out of the 接口规则 table (one-row labels)."""
    m = re.search(
        rf"{re.escape(label)}\s*</(?:td|th)>\s*<(?:td|th)[^>]*>([^<]+)</",
        desc_html,
    )
    return m.group(1).strip() if m else None


def render_scaffold(api_id: str, method_name: str, desc_html: str) -> str:
    """Render the auto-generated portion of a per-endpoint .md file."""
    method = extract_field(desc_html, "请求方法") or "?"
    path = extract_field(desc_html, "请求地址") or "?"
    service = extract_field(desc_html, "所属服务") or "?"
    rate = extract_field(desc_html, "频控策略") or "?"

    text = html_to_text(desc_html)

    out = [
        f"# {method_name}",
        "",
        f"> Auto-generated from `docs/api-raw/{api_id}.json`. Anything below "
        f"`{INTEGRATION_HEADER}` is hand-edited; the auto-generated section "
        f"is regenerated by `scripts/render_endpoint_docs.py` — do not edit "
        f"above the marker.",
        "",
        "## Contract",
        "",
        f"- **Method**: `{method}`",
        f"- **Path**: `{path}`",
        f"- **Service**: {service}",
        f"- **Rate limit**: {rate}",
        f"- **apiId**: `{api_id}`",
        "",
        "## Upstream documentation (raw)",
        "",
        "```text",
        text[:8000],
        "```" if len(text) <= 8000 else f"```\n... (truncated; full text in docs/api-raw/{api_id}.json)",
        "",
        INTEGRATION_HEADER,
        "",
        "_(not yet documented)_",
        "",
    ]
    return "\n".join(out)


def merge_with_existing(scaffold: str, existing_path: Path) -> str:
    """Preserve hand-edited Integration notes section."""
    if not existing_path.exists():
        return scaffold
    existing = existing_path.read_text()
    if INTEGRATION_HEADER not in existing:
        return scaffold
    _, hand_part = existing.split(INTEGRATION_HEADER, 1)
    auto_part, _ = scaffold.split(INTEGRATION_HEADER, 1)
    return auto_part + INTEGRATION_HEADER + hand_part


def main() -> None:
    missing = []
    for api_id, (group, slug) in LAYOUT.items():
        raw_path = RAW / f"{api_id}.json"
        if not raw_path.exists():
            missing.append(api_id)
            continue
        raw = json.loads(raw_path.read_text())
        data = raw.get("data") or {}
        method_name = data.get("methodName") or slug
        desc_html = data.get("methodDesc") or ""
        scaffold = render_scaffold(api_id, method_name, desc_html)
        out_path = OUT / group / f"{slug}.md"
        out_path.parent.mkdir(parents=True, exist_ok=True)
        merged = merge_with_existing(scaffold, out_path)
        out_path.write_text(merged)
        print(f"  wrote {out_path.relative_to(REPO)}")
    if missing:
        print(f"\n  missing raw JSON for: {missing}")


if __name__ == "__main__":
    main()
